@startuml
|Дорожка 1: Пользователь|
start
|Дорожка 1: Пользователь|
:Регистрация / Вход в систему;
|Дорожка 2: Система|
:Обработка регистрации пользователя;

if (Регистрация успешна?) then (да)
|Дорожка 1: Пользователь|
:Поиск товара;
|Дорожка 2: Система|
:Идентификация запросов поиска;
|Дорожка 1: Пользователь|
    :Ввод ключевых слов;
    --> [Задача] :Фильтрация и сортировка товаров;
|Дорожка 2: Система|
:Формирование списка товаров;
|Дорожка 1: Пользователь|
    :Применение фильтров;
|Дорожка 2: Система|
:Формирование результатов фильтрации;
|Дорожка 1: Пользователь|
    :Выбор товара;
|Дорожка 2: Система|
:Отображение карточки товара;
:Отправка карточки товара к пользователю;
|Дорожка 1: Пользователь|
    :Просмотр карточки товара;
    if (Товар выбран?) then (да)
        :Добавление товара в корзину;
        :Выбор размера/цвета;
        :Нажать "Добавить в корзину";
|Дорожка 2: Система|
:Обработка добавления товара в корзину;
|Дорожка 1: Пользователь|
    endif
    :Просмотр корзины;
|Дорожка 2: Система|
:Формирование информации о товарах в корзине;
|Дорожка 1: Пользователь|
    :Изменить количество / Удалить товар;
    :Оформление заказа;
|Дорожка 2: Система|
:Обработка оформления заказа;
|Дорожка 1: Пользователь|
    :Ввод адреса доставки и выбора способа оплаты;
    :Подтверждение заказа;
|Дорожка 2: Система|
:Генерация уведомления о новом заказе;
|Дорожка 1: Пользователь|
    --> [Задача] :Отслеживание заказа;
    :Отслеживание статуса заказа;
|Дорожка 2: Система|
:Организация доставки;
|Дорожка 1: Пользователь|
    :Получение товара;
    :Оставить отзыв о товаре;
|Дорожка 2: Система|
:Получение отзыва;
:Фиксация отзывов пользователей о полученных товарах;
endif
end
@enduml