@startuml

state Создан {
    [*] --> Created
    Created --> Авторизован : Регистрация
    Created --> Авторизован : Вход в систему

    state ВыполняющаяДеятельность {
        do: Обработка запросов пользователя.
    }

    Авторизован --> Корзина : Добавление товара в корзину
    Авторизован --> ОформлениеЗаказа : Оформление заказа

  
    entry: Инициализация сессии пользователя.
    
    exit: Сохранение информации о сессии.
    
    do: Обработка всех текущих запросов пользователя.

    Created --> ОжиданиеПодтверждения : WaitConfirm
    Авторизован --> ОжиданиеПодтверждения
}

state ОжиданиеПодтверждения {
    [*] --> WaitConfirm

    WaitConfirm --> ЗаказЗавершен : Подтверждение заказа
    note right: Активность: Генерация уведомления о новом заказе

    WaitConfirm --> [*] : Отказ от заказа
    note right: Активность: Удаление заказа из системы
}

state Корзина {
    [*] --> Корзина

    Корзина --> ОформлениеЗаказа : Переход к оформлению заказа
    do: Подсчет общей стоимости товаров в корзине
    entry: Подгрузка нужных товаров из базы данных для отображения
    exit: Сохранение изменений в корзине пользователя
}

state ЗаказЗавершен {
    [*] --> Завершен

    Завершен --> ПолучениеТовара : Получение товара
    Завершен --> ОжиданиеДоставки : Ожидание доставки
    note right: Передача товара покупателю
    note right: Доставка завершена
    entry: Отправка уведомления о завершении заказа
    do: Мониторинг статуса доставки заказа
    exit: Закрытие заказа
}

@enduml