@startuml
'Пользователь --> Корзина : 1.1
Пользователь : + userId: Integer
Пользователь : + имя: String
Пользователь : + email: String
Пользователь : + пароль: String
Пользователь : зарегистрироваться(): void
Пользователь o-- Корзина

Корзина : + userId: Integer
Корзина: + товары: List<Товар>




@enduml