@startuml
actor Покупатель
actor Система
actor ПлатежныйШлюз
Покупатель -> Система: Заказ товара
Покупатель -> Система: Выбрать товары
Система -> Система : Проверка наличия товаров на складе


alt Есть в наличии достаточное кол-во
Система-> Система : Зарезервировать товар
Система --> Покупатель: //Показать подтверждение заказа//

else Нет в наличии достаточного кол-ва
Система --> Покупатель : Показать сообщение "Нет в наличии"
end
Система -> Покупатель : Предложить выбрать карту для оплаты
Покупатель -> Система : Выбор карты

alt Есть прикрепленная карта
Система-> Система : Проверить привязку карты к профилю
Система --> Покупатель: Показать карту и ее последние цифры

else Нет прикрепленной карты
Система --> Покупатель : Показать сообщение "Добавить карту"
Система -> Покупатель : Предложить ввести данные карты
Покупатель -> Система : Сохранить данные карты для оплаты
end
Покупатель -> Система: Перейти к оформлению заказа
Система -> Система : посчитать общую стоимость

loop Оплата не завершена 5 минут
Система -> ПлатежныйШлюз : Перенаправить на страницу оплаты
ПлатежныйШлюз -> ПлатежныйШлюз : Проверить оплату
end

opt Оплата завершена
ПлатежныйШлюз --> Система : Отправить подтверждение оплаты
Система --> Покупатель : Показать подтверждение заказа
end

@enduml