@startuml
actor Пользователь as User
participant "Приложение" as App
participant "Кеш" as Cache
participant "Основная БД" as Database
activate Cache
activate App
activate Database

User -> App: запрос
App -> Cache : Пишем данные
Cache -> Database: Сохраняем в бд
Database --> Cache : Ответ
Cache -> Cache : Сохранить данные в Кеш
Cache --> App : Ответ


@enduml